{% set version = "6.3.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-delaporte
  version: {{ version|replace("-", "_") }}

source:
  fn: Delaporte_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/Delaporte_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/Delaporte/Delaporte_{{ version }}.tar.gz
  sha256: e0778e3837eab3c5a0884b7d2b51671e479a775a9423e2edda8d566fac289830

build:
  number: 1000
  merge_build_host: True  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - {{compiler('c')}}    # [not win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('Delaporte')"  # [not win]
    - "\"%R%\" -e \"library('Delaporte')\""  # [win]

about:
  home: https://bitbucket.org/aadler/delaporte
  license: BSD_2_clause
  summary: Provides probability mass, distribution, quantile, random-variate generation, and
    method-of-moments parameter-estimation functions for the Delaporte distribution.
    The Delaporte is a discrete probability distribution which can be considered the
    convolution of a negative binomial distribution with a Poisson distribution. Alternatively,
    it can be considered a counting distribution with both Poisson and negative binomial
    components. It has been studied in actuarial science as a frequency distribution
    which has more variability than the Poisson, but less than the negative binomial.
  license_family: BSD

extra:
  recipe-maintainers:
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
