# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "R+Qo/lEVc+/EQExOOjDbTdcVXW80xvgdbH+GsnPBfqTVYYjWzUDltIsk1rzmgHxUC+zpxjXbOUXczHcr76RuPSVM73dQYZLT4Z4gporHt7w2XlCaZ1IVewzXM7IgVc6ldYznKZOU6pdres8RbNYtSRdBDdhNjBvLBePfH3f6Ai2jqEJt1miJO65sbg3TOwmIc5Ny00IgRVp5nh7qa6eJOJ1MudrBsPmoIYO8xWT1eOhQ2U+yjP9zfWPoUxyJ1JG+UJok6vA5xOFFUMd7YmevquOzja/YgDf2+eT/zWiiT4dO+ENbdHvtQArEWCdmyHY8/ajxLI15pw89eiBuexYICc94JBOSNeHtWmBwBtiKNT/8O41kuIjFNBHWwuJeKr6+ooafwaeNFFdg6oM8MOypGqaga+CUoxydbqcyiyIMhWvcpU0glEyUKGSGDzAplHxhPWcwvxab9NgW57QFb6L2jBBbRvqtVN+F9t+NNHpgl/hTnk0rZOr3B/Ux9tE72ET095a3aQlgxYiCQFEh+AJ3koPYy/8DiHVmjtbfKr9DPK4Tc6bgCndOljBNZ4Akv+4Mf0tPmvOJIzdtOwnA8YB7lmV6yVm+PYCmdZ0zYaJlN/wfBslSBKf4Ryfdp8WCDdR4fOSLHrfQsIAIDkQ/udacVVgu18eb6bAR+cp1sLFgItI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
