travis:
  secure:
    BINSTAR_TOKEN: BmTENh2HK/faUUb90MKoa3kobWSZEu/dSP/5I5EYcf2tbAu4JjucSZGLyqska5upUVds1XE1fBJ3Kpjq532mLYKahzDsYbH/i/Z6shgIO6qXsjy0MAVcBK2M7lP+cpuDPJVFsRs8rhKN7Gsf7PW/B2930T5niixXuspfIVscv5T+bqFhdS9/tq6c2MD6STqzc7St/mDB3IK1rs+zu+UwVW0obzCylRabXQI8iWwJjgq7HVHbWYZ0EmS0mJ4fvzW4hIoBIqx7wxZeGcQZ8xyyiBb1tVKT36VvF4sPkPCno5lLwpWqykfyotfH4C0vHgI/jopGBuvlfsjU8UCpFzQYOiXGE6w1CRj79VX0qci2srIrDkOBKsgKNOfnKVsHph/QzF7rkte+6NX78QyLVgx9bo9h8xVMXRibRzjpwJ07OObtyNr0MVKHa/V03GpiHH1+1L6hGv8Da4EUXO6xmpNUdyodRd0VS8OSSCCO0frPE39TxOdxLPS1Z9hOwMVFF3h+0Igje8J1YIPuCHU7kqCylKdvrV/xXOKeWO7gNSKgEcrAAakGTF2hDzazSJ9MDuS3RMmN1aCwnYLHynpUQyTKBh/DRzJiLSWPYY05Zhv8oBlK1ECEMx0WZrc4F9AVzIpFqR29p9t3sQHjQ6HpmY1hpc3ODa7Jazia8mIUPajW4Rs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
