appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: iSafwgYs0F8g1q3t3v0TcN0UgKlWkz4qJqgVVqJf3COYMRAP8PpsjBp3u2/EHdwSXZ17zaaL5vQhBDCxDC7SYJCq8z3ObqfDf6Wfgpk9rzSaK3rg75PjJsyg2nDDow52putaU980cFHeitYVFnxa1serRNDYjw0l1y7I5twDGw6V5vUG5x8nvNnntwXOY3DHF+lxzcG3AK4OYYNMolfcPtMhNEJSvLcs1bg3/CNl/gA4LsLL5vqgVJec87K0QykiSdqwn2t5cRVX3/hM5flpGEokA7LoxR2P4pLE3voSpCQJCnBcrsmoJNbTKhqtzk7Gtvh9CaQlvmYf1CIU9F+hNQoY8Pbq5Vflu+SS9zdkVvM+SKlT0E8y6LZRQmuUbfi1bHHg8uGTzCjtDeIRetxwgwFs3NKncKTgKmbCIxvkWSB8rqlwNVcyPMEG7OYmWM0Z3VGlMdg8fT49pBBoVqoiDaL+2d7S7UY5F8u1D3O+P0ytXo7OCJTyGtpEig0GfhxzupAvICPdaVqRgw+eegmobWYYFoDusEozSg2dfH8bnKaZb4cbNgoh6j56KeCjnOu+yI/PuHcOL6iNwgHvjxH5SLxxvVJEQ6XSGt0rU2NPYQx0w4Bxwdp7CXTWb1eGQHwpu9OrwYNxEs5ImKAsxO6UR0DDvb+XHSfsz9HrmyXNPzM=}
bot:
  automerge: true
